email:
  mailhost:
    - smtp.163.com
    - 465
  fromaddr: alanwu77@163.com
  toaddrs:
    - alanwoo77@hotmail.com
  subject: Error Log from FactorUpdater
  credentials:
    - alanwu77@163.com
    - JLZAUDaf77acbDvT
  secure: ssl